// @harness/procedural: see docs/decisions/0011-procedural-graph.md and docs/plans/procedural-graph.md.
export { canonicalJson, sha256Hex } from "./canonical.ts";
export { compilePath, composeCandidate, compositionJsonSchema, CompositionSettingsSchema, parseCompositionSettings, pathCandidates, recordedRuns, revisionTools, StagingLibrary, workflowBinding, type CompileResult, type Composition, type CompositionSettings, type PathCandidate, type RecordedCall, type WorkflowBinding } from "./compose.ts";
export { DEFAULT_SELECT, modelRefiner, runDream, type Approver, type Composer, type DreamPorts, type DreamResult, type Evaluator, type Refiner, type RunDreamOptions, type TrajectorySource } from "./dream-runner.ts";
export { absorbedEntries, CompositionSchema, DreamEventSchema, dreamStart, dreamStep, RolloutResultSchema, tailTokens, type DreamCommand, type DreamComposition, type Tokenizer, type DreamEvent, type DreamInput, type DreamOutcome, type DreamRefineRequest, type DreamState, type DreamStep, type Rejection, type RolloutResult, type RoundOutcome } from "./dream.ts";
export { applyEdits, prepareCandidate, type PreparedCandidate, type PrepareOptions, type RepairedEdge } from "./edits.ts";
export { proceduralExtension, type ProceduralAction, type ProceduralExtensionOptions } from "./extension.ts";
export { editFilter, type EntropyOptions, type FilterCode, type FilterFinding, type FilterOptions } from "./filter.ts";
export { anchoredNonInferiority, approvalGate, atLeastRetained, evidenceGate, graphSize, normalQuantile, pairedDifference, poorStatistics, powerMargin, routesIntoSideEffects, structureGate, type EvidenceBar, type EvidenceGateInput, type GateResult, type GraphSize, type NonInferiorityEvidence, type PairedDifference, type TaskScore } from "./gates.ts";
export { BindingSchema, CandidateDocumentSchema, checkGraph, DecisionSchema, DEFAULT_NODE_TYPES, DEFAULT_RELATIONS, DIAGNOSTIC_CODES, DiagnosticSchema, DreamIdSchema, EditSetSchema, editSetJsonSchema, END, EntryIdSchema, FORMAT, GraphEdgeSchema, GraphIdSchema, graphJsonSchema, GraphNodeSchema, incoming, nodeById, NodeNameSchema, NodeTypeNameSchema, outgoing, parseGraph, ProceduralGraphSchema, RelationNameSchema, revisionId, RevisionIdSchema, RevisionRecordSchema, ScoreSchema, seedGraph, START, TrajectoryIdSchema, type Binding, type CandidateDocument, type CyclePolicy, type Decision, type Diagnostic, type DiagnosticCode, type DreamId, type EditSet, type EntryId, type GraphEdge, type GraphId, type GraphNode, type NodeName, type NodeTypeName, type ParsedGraph, type ProceduralGraph, type RelationName, type RevisionId, type RevisionRecord, type Score, type TrajectoryId } from "./graph.ts";
export { guide, GuidanceCache, type GuidanceKeyParts, type GuideRequest } from "./guide.ts";
export { exportGraph, graphHistory, importGraph, readGraph, revertGraph, type ClockLike, type ExportResult, type GraphHistory, type GraphView, type ImportResult, type RevertResult, type RevisionSummary } from "./import-export.ts";
export { LiveLearner, type LearnerEvent, type LearnerResult, type LiveLearnerDeps } from "./learner.ts";
export { match, neighborhood, type MatchMode, type Neighborhood } from "./locate.ts";
export { MemoryProceduralStore, redactRecord, STORE_FORMAT, TOMBSTONE, type ProceduralStoreDocument } from "./memory-store.ts";
export { exportMermaid } from "./mermaid.ts";
export { decayedSupport, differenceBounds, proposals, statusChanges } from "./overlay-policy.ts";
export { coreView, EntryStatusSchema, OverlayEntrySchema, OverlayEventSchema, type Arm, type EdgeStats, type EffectiveEdge, type EffectiveGraph, type EffectiveNode, type EntryEvidence, type EntryStatus, type OverlayEntry, type OverlayEvent, type OverlayState, type TransitionStats } from "./overlay-types.ts";
export { edgeKey, effectiveGraph, emptyOverlay, entryId, exposed, foldAll, foldOverlay, MAX_SESSIONS, MAX_TURNS, rebaseOverlay } from "./overlay.ts";
export { latestOn, overlayAt, overlayBases, pinSession, readOverlay, SALT_BYTES, type PinRequest } from "./pinning.ts";
export { parsePlan, PLAN_RELATIONS, planFromSubgraph, PlanPayloadSchema, type PlanOptions, type PlanPayload, type PlanRelations, type PlanResult } from "./plan.ts";
export { AccessPolicySchema, ACTIONS, authorize, globMatches, parsePolicy, policyJsonSchema, type AccessPolicy, type Action } from "./policy.ts";
export { projectTurn, turnProjection, type LogEntryLike, type LogGap, type ProjectionContext, type ScoreSource, type TurnProjection, type VersionPair } from "./projection.ts";
export { readJsonBlock, renderPrompt, type Decoding } from "./prompt.ts";
export { logTrajectories, type SessionLog } from "./recorded.ts";
export { refine, type RefineRequest, type RefineResult } from "./refine.ts";
export { modelReflector, reflect, reflectionJsonSchema, type Reflector, type ReflectRequest } from "./reflect.ts";
export { explainResolve, explainRoute, matches, parseResolver, ResolverSchema, resolveGraph, resolverJsonSchema, RouteSchema, routeGraph, WhenSchema, type GraphRouter, type Resolution, type ResolveContext, type Resolver, type Route, type RouteAnswer, type RouteCandidate, type RouteRequest, type When } from "./resolver.ts";
export { GRAPH_TOOL, modelGraphRouter } from "./routing.ts";
export { serializeGraph, serializeNeighborhood, serializeWindow } from "./serialize.ts";
export { GATES, guidancePromptOf, HOPS, parseSettings, PLACEHOLDERS, presetOf, SettingsSchema, settingsJsonSchema, WINDOW, type DreamSettings, type Gate, type LiveSettings, type Preset, type Settings } from "./settings.ts";
export { PinSchema, ProceduralStoreDocumentSchema, SnapshotProceduralStore } from "./snapshot-store.ts";
export { ADVISORY, GUIDANCE_LABEL, proceduralStep, StepRecordSchema, type ProceduralStepDeps, type ProceduralStepHook, type StepInput, type StepNotice, type StepRecord, type StepScope, type TurnInput } from "./step.ts";
export type { AppendLog, Head, Lease, Pin, ProceduralStore } from "./store.ts";
export { ScoredTrajectorySchema, type ScoredTrajectory } from "./trajectory.ts";
